title: Navil Shah
subtitle: A Github Page theme development using Forty by jekyllthemes
email: navil.shah@wickertenexzellenz.com
description: A playground theme development and research project
baseurl: ""
url: https://navilshah.github.io
author: Navil Shah
street_address: Navranpura,
city: Ahmedabad
state: GJ
zip_code: 380009
country: India
phone: 97 25 6 36929
tiles-source: pages
tiles-count: 6
500px_url:
facebook_url: 
github_url: https://github.com/navilshah
gitlab_url: https://gitlab.com/u/navilshah
googleplus_url: 
instagram_url: 
linkedin_url: 
pinterest_url:
slack_url:
twitter_url: 
markdown: kramdown
sass:
  style: compressed
